# Generated by Django 3.0.5 on 2022-01-03 02:36

from django.db import migrations, models
import recipe_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_auto_20211227_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[recipe_api.validators.validation_hex], verbose_name='цвет'),
        ),
    ]
