# Generated by Django 3.0.5 on 2022-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0003_auto_20220103_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
    ]
